package org.jax.mgi.fewi.hunter;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents an ElasticSearch LOOKUP JOIN query.
 * <p>
 * This class extends {@link ESQuery} to support performing JOIN operations
 * across multiple indices in ElasticSearch using the LOOKUP JOIN syntax.
 * </p>
 * 
 * <p>Example usage:
 * <pre>{@code
 * POST /_query
 * {
 *   "query": """
 *     FROM gxd_result_has_image METADATA _id
 *     | LOOKUP JOIN gxd_image_pane ON resultKey
 *     | LOOKUP JOIN gxd_consolidated_sample ON strain
 *     | WHERE markerSymbol == "Wnt1"
 *     | KEEP resultKey, imagePaneKey, imageID, pixeldbID, imageLabel, paneX, paneY, METADATA
 *     | WHERE imageID is not NULL
 *     | LIMIT 50
 *   """
 * }
 * }</pre>
 * 
 * <p>Explanation:</p>
 * <ul>
 *   <li><b>mainIndex:</b> The primary index for the query (e.g., gxd_result_has_image)</li>
 *   <li><b>lookupIndexes:</b> List of {@link ESLookupIndex} objects representing
 *       lookup indices and their join fields.</li>
 *   <li><b>extraStatements:</b> Additional query statements appended as needed.</li>
 * </ul>
 * 
 * <p>Notes:</p>
 * <ul>
 *   <li>The first WHERE clause is typically generated by {@link SearchParams}, e.g., WHERE markerSymbol == "Wnt1".</li>
 *   <li>The LIMIT clause is also generated by {@link SearchParams}.</li>
 *   <li>Prerequisites for LOOKUP JOIN: The lookup index must have the appropriate type configured.</li>
 * </ul>
 * 
 * @see ESQuery
 * @see ESLookupIndex
 */

public class ESLookup extends ESQuery {
	
    /**
     * List of lookup indices to join with the main index.
     */	
	protected List<ESLookupIndex> lookupIndexes = new ArrayList<ESLookupIndex>();
	
    /**
     * Converts this object into a query string, including any configured LOOKUP JOIN statements.
     *
     * @param whereCause The WHERE clause to include in the query.
     * @param size The maximum number of results to return.
     * @param isGroupCountOnly If true, only generates a group count query.
     * @return The fully constructed query string.
     */	
	@Override
	public String toQuery(String whereCause, int size, boolean isGroupCountOnly) {
		
		for ( ESLookupIndex lookupIndex: this.lookupIndexes) {
			this.lookupJoinStatements.add("LOOKUP JOIN " + lookupIndex.getIndexName() + " ON " + lookupIndex.getJoinFieldName());
		}
		
		return super.toQuery(whereCause, size, isGroupCountOnly);
	}
	
	public List<ESLookupIndex> getLookupIndexes() {
		return lookupIndexes;
	}
	public void setLookupIndexes(List<ESLookupIndex> lookupIndexes) {
		this.lookupIndexes = lookupIndexes;
	}

}
