#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`


if [ ! -e ./Configuration ]; then
  echo "Could not find Configuration file."
  exit 1
fi
. ./Configuration

# Prepare
if [ ! -e ${FEWI_PROPERTIES} ]; then
  echo "Could not find ${FEWI_PROPERTIES} "
  exit 1
fi
echo "Copying fewi.properties."
cp ${FEWI_PROPERTIES} ./src/main/webapp/WEB-INF/properties/fewi.properties

if [ ! -e ${WEB_RESOURCES}/GlobalConfig.properties ]; then
  echo "Could not find ${WEB_RESOURCES}/GlobalConfig.properties "
  exit 1
fi
echo "Copying GlobalConfig.properties"
cp ${WEB_RESOURCES}/GlobalConfig.properties ./src/main/webapp/WEB-INF/properties/
echo "Copying templates"
cp ${WEB_RESOURCES}/*.html ./src/main/webapp/WEB-INF/jsp/templates/

# build
if [ ! -e "${MAVEN_REPO_LOCAL}" ] ; then
  echo "MAVEN_REPO_LOCAL is not defined or does not exist."
  exit 1
fi
echo "Building fewi.war"
mvn -Dmaven.repo.local=${MAVEN_REPO_LOCAL} clean package

# deploy
if [ $? -eq 0 ] ; then
    echo "Deploying fewi.war to ${DEPLOY_DIR}"
    cp ./target/fewi.war  ${DEPLOY_DIR}

    if [ ${DEPLOY_BATCH_DIR} != "" ] ; then
        echo "Deploying fewi.war to ${DEPLOY_BATCH_DIR}"
        cp ./target/fewi.war  ${DEPLOY_BATCH_DIR}
    fi
fi
